version: '3.8'

services:
  db:
    image: ankane/pgvector
    container_name: fashion_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fashion_admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: fashion_ai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

